### ISSUE TITLE
Bug : Setting unknown property: yii\console\Application::vendor

### ISSUE THREAD

**Issue by jomonkj** [hiqdev/hidev#8]
```
root:publishare-master# ./vendor/bin/hidev 
Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Application::vendor'

in /project/publishare/publishare-master/vendor/yiisoft/yii2/base/Component.php:209

Stack trace:
#0 /project/publishare/publishare-master/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('vendor', Array)
#1 /project/publishare/publishare-master/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(yii\console\Application), Array)
#2 /project/publishare/publishare-master/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#3 /project/publishare/publishare-master/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#4 /project/publishare/publishare-master/vendor/hiqdev/hidev/bin/hidev(20): yii\console\Application->__construct(Array)
#5 {main}

```

**Comment by jomonkj** [comment]
It was my problem. 
wrong versions of dependencies
